artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shanan-shetty-321/datasets/raw/refs/heads/main/Chicken-fecal-images.7z
  local_data_file: artifacts/data_ingestion/data.7z
  unzip_dir: artifacts/data_ingestion/unzip
  
  