artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shanan-shetty-321/datasets/raw/refs/heads/main/Chicken-fecal-images.7z
  local_data_file: artifacts/data_ingestion/data.7z
  unzip_dir: artifacts/data_ingestion/unzip


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5   #only pretrained model
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5  #updated model with custom layers u added 


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5 #after running/train some epochs it will save model

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
